spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/fiasdb?currentSchema=fias
    username: postgres
    password: postgres
#    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fias
        jdbc:
          batch_size: 80
  flyway:
    enabled: true
    schemas: fias
    url: jdbc:postgresql://localhost:6543/fiasdb
    user: postgres
    password: postgres
    baseline-on-migrate: true
    locations: classpath:database/migration
server:
  servlet:
    contextPath: /addressSearcher