spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fiasdb
    username: postgres
    password: postgres
#    schema: fias
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fias
        #ddl-auto: validate
#        generate-statistics: true
#        jdbc:
#          batch_size: 30
#        order_inserts: true
  flyway:
    enabled: true
    schemas: fias
    url: jdbc:postgresql://localhost:5432/fiasdb
    user: postgres
    password: postgres
    baseline-on-migrate: true
    #validate-on-migrate: true
    #datasources:
    #  default:
    locations: classpath:database/migration

server:
  servlet:
    contextPath: /addressSearcher