spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fiasdb?currentSchema=fias
    username: # username
    password: # password
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fias
        jdbc:
          batch_size: 80
  flyway:
    enabled: true
    schemas: fias
    url: jdbc:postgresql://localhost:5432/fiasdb
    user: # username
    password: # password
    baseline-on-migrate: true
    locations: classpath:database/migration
server:
  port: 8090
  servlet:
    contextPath: /addressSearcher
